-- low grav buff, reduces gravity for 10 seconds - doesn't work well, used for tests and template
function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		-- react to collision
		if message.other_group == hash("char") then
			-- move out of view
			go.set_position(vmath.vector3(0, -100, 0))
			-- activate buff effects
			
			
			timer.delay(5, false, end_buff)
		end
	end
end

function end_buff(self)
	go.delete(".")
end